### ISSUE TITLE
API url change random.cat

### ISSUE THREAD

**Issue by Reforced** [FranciscoG/DerpyBot#45]
The API url was changed, the old one in `bot/commands/fun/cat.js` isn't working anymore.
New url should be [http://aws.random.cat/meow](http://aws.random.cat/meow) now.

**Comment by FranciscoG** [comment]
thanks for informing me! Will update shortly

**Comment by FranciscoG** [comment]
api updated. fixed in v1.23.1 that I just release
thanks!
